[versions]
# https://fabricmc.net/develop/
fabric_loom = "1.14-SNAPSHOT"
minecraft = "1.21.10"
fabric_loader = "0.18.1"
fabric_kotlin = "1.13.7+kotlin.2.2.21"
fabric_api = "0.138.3+1.21.10"
# https://docs.papermc.io/adventure/platform/modded/#dependency
advntr = "6.7.0"
# https://github.com/Patbox/sgui/releases
sgui = "1.11.0+1.21.9"
# https://maven.nucleoid.xyz/eu/pb4/polymer-core/
polymer = "0.14.3+1.21.10"
# https://maven.nucleoid.xyz/xyz/nucleoid/server-translations-api/
servertranslations = "2.5.2+1.21.9-pre3"
# https://github.com/JetBrains/Exposed/releases
exposed = "1.0.0-rc-4"
# https://github.com/xerial/sqlite-jdbc/releases
sqlite = "3.51.1.0"
# https://mvnrepository.com/artifact/org.postgresql/postgresql
pgsql = "42.7.8"
# https://jitpack.io/#Phyrone/brigardier-kotlin
brigadierkt = "1.4.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
fabric_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_kotlin" }
advntr = { module = "net.kyori:adventure-platform-fabric", version.ref = "advntr" }
sgui = { module = "eu.pb4:sgui", version.ref = "sgui" }
polymer-core = { module = "eu.pb4:polymer-core", version.ref = "polymer" }
polymer-resourcepack = { module = "eu.pb4:polymer-resource-pack", version.ref = "polymer" }
servertranslations = { module = "xyz.nucleoid:server-translations-api", version.ref = "servertranslations" }

exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
pqsql-jdbc = { module = "org.postgresql:postgresql", version.ref = "pgsql" }
brigadierkt = { module = "com.github.Phyrone:brigardier-kotlin", version.ref = "brigadierkt" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
